apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-album-api
spec:
  selector:
    matchLabels:
      app: photo-album-api
  template:
    metadata:
      labels:
        app: photo-album-api
    spec:
      containers:
        - name: photo-album-api
          image: docker.io/priyankass99/photo-app-album-api:1.0.0
          ports:
            - containerPort: 3001
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "<AWS_ACCESS_KEY_ID>"
            - name: AWS_SECRET_ACCESS_KEY
              value: "<AWS_SECRET_ACCESS_KEY>"
